# Generated by Django 3.2.25 on 2025-04-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart_cart',
        ),
    ]
